# Generated by Django 6.0.3 on 2026-05-04 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.IntegerField()),
                ('reference', models.IntegerField()),
                ('identifier', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_currency', models.CharField(max_length=31)),
                ('fees_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees_currency', models.CharField(max_length=31)),
                ('date', models.DateTimeField(db_index=True)),
                ('trid', models.IntegerField(db_index=True, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Refunded'), (3, 'Error'), (4, 'Canceled'), (5, 'Expired')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
