# Generated by Django 6.0.3 on 2026-05-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulariopagamento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
