# Generated by Django 5.2.15 on 2026-06-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSubscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
